Python_advanced_course/Home_work_12_Django_blog/blog/urls.py
from django.urls import path

from . import views
from .views import BlogsView, CategoryView, PostUpdateView, PostDetailView, PostCreateView

app_name = "blog"

urlpatterns = [
    # path('', views.main, name='main'),
    path('', BlogsView.as_view(), name='view_all'),
    # path('post/<post_id>/', views.certain_post, name='certain_post'),
    # path('item_view/<post_id>/', ItemView.as_view(), name='item_view'),
    path('item/<post_id>/', PostDetailView.as_view(), name='detail_view'),
    # path('add/', views.add, name='add_post'),
    path('view_add/', PostCreateView.as_view(), name='view_add'),
    path('add_category/', views.add_category, name='add_category'),
    path('filter/<int:cat_id>/', views.filter_by_category, name='filter_by_category'),
    path('filter_user/<user_id>/', views.filter_by_user, name='filter_by_user'),
    # path('all_category/', views.all_category, name='all_category'),
    path('all_category_view/', CategoryView.as_view(), name='all_category_view'),
    path('edit/<post_id>/', PostUpdateView.as_view(), name='post_update'),
]

Python_advanced_course/Home_work_12_Django_blog/myblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('user/', include('user.urls')),
    # *staticfiles_urlpatterns(),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    ]

Python_advanced_course/Home_work_12_Django_blog/blog/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}(id:{self.pk})'


class Post(models.Model):
    category = models.ManyToManyField(Category)
    headline = models.CharField(max_length=255)
    writer = models.ForeignKey(User, null=True, blank=True, default=None, on_delete=models.CASCADE)
    text = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, allow_unicode=True)

    def __str__(self):
        return f'{self.pk}: {self.headline}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = f'{str(self.headline).lower().replace(" ", "-").replace("/", "-")[:20]}'\
                        + f'{str(self.text).lower().replace(" ", "-").replace("/", "-")[:5]}'
        super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        from django.urls import reverse
        # return reverse('blog:certain_post', kwargs={'post_id': self.slug})
        return reverse('blog:item_view', kwargs={'post_id': self.slug})

Python_advanced_course/Home_work_12_Django_blog/blog/forms.py
from django import forms

from .models import Post, Category


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('category',
                  'headline',
                  'writer',
                  'text')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', )

Python_advanced_course/Home_work_12_Django_blog/blog/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, UpdateView, DetailView, CreateView
# Create your views here.


from .forms import PostForm, CategoryForm
from .models import Post, Category


# def main(request): # Function returns main page
#     titles = Post.objects.all()
#     return render(request,
#                   'blog/main.html',
#                   context={'titles': titles, 'header': 'Main page'})


# def certain_post(request, post_id: int):  # Function returns one post by slug
#     title = Post.objects.get(slug=post_id)
#     category = title.category.all()
#     return render(request, 'blog/certain_post.html',
#                   context={'title': title, 'category': category, 'header': 'Certain post'})


# def all_category(request):  # Function to display all categories
#     all_cat = Category.objects.all()
#     return render(request, 'blog/all_category.html',
#                   context={'all_cat': all_cat, 'header': 'All category'})


def filter_by_category(request, cat_id: int):  # Function that displays posts filtered by category name
    category = Category.objects.get(pk=cat_id)
    titles = Post.objects.filter(category=category.pk)
    return render(request, "blog/filter_by_category.html",
                  context={'titles': titles, 'category': category, 'header': 'Filter by caegory'})


def filter_by_user(request, user_id: int):  # Function that displays posts filtered by category name
    user = User.objects.get(pk=user_id)
    titles = Post.objects.filter(writer=user.pk)
    return render(request, "blog/filter_by_user.html",
                  context={'titles': titles, 'header': 'Filter by user'})


# @login_required
# def add(request):  # Function to add a new post
#     # if request.user in User.objects.all():
#     if request.method == 'POST':
#         form = PostForm(data=request.POST)
#         if form.is_valid():
#             form_name = request.POST.get('headline')
#             if Post.objects.all().filter(headline=form_name):
#                 error = 'Headline already exist'
#                 return render(request, 'blog/add_post.html',
#                               context={'form': form, 'error': error, 'header': 'Add new category'})
#             new_post = form.save(commit=False)
#             new_post.writer = request.user
#             new_post = form.save()
#             return redirect('blog:certain_post', post_id=new_post.slug)
#         return render(request, 'blog/add_post.html', context={'form': form, 'header': 'Add post'})
#     form = PostForm
#     return render(request, 'blog/add_post.html', context={'form': form, 'header': 'Add post'})
#     # return redirect('blog:main')

@staff_member_required(redirect_field_name='blog/main.html')
def add_category(request):  # Function to add a new category
    if request.method == 'POST':
        form = CategoryForm(data=request.POST)
        if form.is_valid():
            form_name = request.POST.get('name')
            if Category.objects.all().filter(name=form_name):
                error = 'Category already exist'
                return render(request, 'blog/add_category.html',
                              context={'form': form, 'error': error, 'header': 'Add new category'})
            form.save()
            return redirect('blog:all_category_view')
        return render(request, 'blog/add_category.html',
                      context={'form': form, 'header': 'Add new category'})
    form = CategoryForm
    return render(request, 'blog/add_category.html',
                  context={'form': form, 'header': 'Add new category'})


# class ItemView(View):
#     def get(self, request, post_id):
#         title = Post.objects.get(slug=post_id)
#         category = title.category.all()
#         return render(request, 'blog/certain_post.html',
#                       context={'title': title, 'category': category, 'header': 'Certain post'})


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/view_add_post.html'

    def form_valid(self, form):
        post_name = self.request.POST.get('name')
        if Post.objects.all().filter(headline=post_name):
            error = 'Name already exist'
            return render(self.request, 'blog/view_add_post.html', context={'form': form, 'error': error})

        new_post = form.save(commit=False)
        new_post.writer = self.request.user
        new_post.save()
        form.save_m2m()
        return super().form_valid(form)


class BlogsView(ListView):
    model = Post
    context_object_name = 'titles'
    template_name = 'blog/view_all.html'


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'title'
    template_name = 'blog/post_detail.html'
    slug_url_kwarg = 'post_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        if self.object:
            context['categories'] = self.object.category.all()
            context['author'] = self.object.writer
        return context


class PostUpdateView(UpdateView):
    model = Post
    slug_url_kwarg = 'post_id'
    fields = ['headline', 'category', 'text']
    template_name = 'blog/post_edit.html'


class CategoryView(ListView):
    model = Category
    context_object_name = "all_cat"
    template_name = 'blog/all_category_view.html'

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/add_category.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<form action="{% url 'blog:add_category' %}" method="POST">
    {% csrf_token %}
    <p> Please enter name for new category: {{ form.name }} </p>
    <input type="submit" value="Add">
</form>
{% if error %}
    {{error}}
{% endif %}
{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/add_post.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<form action="{% url 'blog:add_post' %}" method="POST">
    {% csrf_token %}
    <p> Category: {{ form.category }} </p>
    <p> Headline: {{ form.headline }} </p>
    <p> Text    : {{ form.text }} </p>
    <input type="submit" value="Add">
</form>
{% if error %}
    {{error}}
{% endif %}




{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/all_category.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<H1>CATEGORIES</H1>
{% for item in all_cat %}
<li>
<a href="{% url 'blog:filter_by_category' cat_id=item.id %}">{{item}}</a>
</li>
{% endfor %}
{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/all_category_view.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<H1>CATEGORIES</H1>
{% for item in all_cat %}
<li>
<a href="{% url 'blog:filter_by_category' cat_id=item.id %}">{{item}}</a>
</li>
{% endfor %}
{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/blog_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/certain_post.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<H1><p>{{ title.headline }}</p></H1>
<H4>Author: <a href="{% url 'blog:filter_by_user' user_id=title.writer.id %}">
    {{title.writer}}</a></H4>
<p></p>
<H5>Categories for this title:</H5>
{% for item in category %}
<li>
<a href="{% url 'blog:filter_by_category' cat_id=item.id %}">{{item}}</a>
</li>
{% endfor %}
<p></p>


<p>{{ title.text }}</p>
<p><strong>Published:  {{ title.publish }}</strong></p>

{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/filter_by_category.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<H3>Posts filtered be category: {{category}}</H3>
{% for item in titles %}
<!--<p>{{item}}</p>-->
<p><a href="{% url 'blog:detail_view' post_id=item.slug %}">{{item}}</a></p>
<p>{{item.text|truncatechars:50}}</p>
{% endfor %}

{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/filter_by_user.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<H3>{{header}}</H3>
{% for item in titles %}
<!--<p>{{item}}</p>-->
<a href="{% url 'blog:detail_view' post_id=item.slug %}">{{item}}</a>
<p>{{item.text|truncatechars:101}}</p>
{% endfor %}

{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/main.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}


{% block content %}
<H2><strong>ALL TITLES</strong></H2>
{% for item in titles %}
<p>
  <a class="item" href="{% url 'blog:item_view' item.slug %}">{{item.publish.date}}---
    {{item.headline|upper}} ({{item.writer}})</a>
    {{ item.text|truncatechars:100 }}...
</p>
{% endfor %}
{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<H1><p>{{ title.headline }}</p></H1>
<H4>Author: <a href="{% url 'blog:filter_by_user' user_id=title.writer.id %}">
    {{title.writer}}</a></H4>
<p></p>
<H5>Categories for this title:</H5>
{% for item in categories %}
<li>
<a href="{% url 'blog:filter_by_category' cat_id=item.id %}">{{item.name}}</a>
</li>
{% endfor %}
<p></p>
<p>{{ title.text }}</p>
<p><strong>Published:  {{ title.publish }}</strong></p>

<p>SLUG: {{ title.slug }}</p>

{% if author.id == user.id %}
<H3><a href="{% url 'blog:post_update' post_id=title.slug %}">Edit</a></H3>
{% endif %}

{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<form method="POST" >
    {% csrf_token %}
    <p>Edit post</p>
    <p>{{ form.headline }}</p>
    {{form.category}}
    {{form.text}}
    <button type="submit">Edit</button>
    {% if error %}
    <p>{{error}}</p>
    {% endif %}
  </form>
</div>
{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/view_add_category.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<form action="{% url 'blog:add_category' %}" method="POST">
    {% csrf_token %}
    <p> Please enter name for new category: {{ form.name }} </p>
    <input type="submit" value="Add">
</form>
{% if error %}
    {{error}}
{% endif %}
{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/view_add_post.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}

{% block content %}
<form action="{% url 'blog:view_add' %}" method="POST">
    {% csrf_token %}
    <p> Category: {{ form.category }} </p>
    <p> Headline: {{ form.headline }} </p>
    <p> Text    : {{ form.text }} </p>
    <input type="submit" value="Add">
</form>
{% if error %}
    {{error}}
{% endif %}

{% endblock %}

Python_advanced_course/Home_work_12_Django_blog/blog/templates/blog/view_all.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock %}


{% block content %}
<H2><strong>ALL TITLES</strong></H2>
{% for item in titles %}
<p>
  <a class="item" href="{% url 'blog:detail_view' item.slug %}">{{item.publish.date}}---
    {{item.headline|upper}} ({{item.writer}})</a>
    {{ item.text|truncatechars:100 }}...
</p>
{% endfor %}
{% endblock %}