Python_advanced_course/Home_work_12_Django_blog/blog/urls.py
from django.urls import path

from . import views
from .views import BlogsView, CategoryView, PostUpdateView, PostDetailView, PostCreateView

app_name = "blog"

urlpatterns = [
    # path('', views.main, name='main'),
    path('', BlogsView.as_view(), name='view_all'),
    # path('post/<post_id>/', views.certain_post, name='certain_post'),
    # path('item_view/<post_id>/', ItemView.as_view(), name='item_view'),
    path('item/<post_id>/', PostDetailView.as_view(), name='detail_view'),
    # path('add/', views.add, name='add_post'),
    path('view_add/', PostCreateView.as_view(), name='view_add'),
    path('add_category/', views.add_category, name='add_category'),
    path('filter/<int:cat_id>/', views.filter_by_category, name='filter_by_category'),
    path('filter_user/<user_id>/', views.filter_by_user, name='filter_by_user'),
    # path('all_category/', views.all_category, name='all_category'),
    path('all_category_view/', CategoryView.as_view(), name='all_category_view'),
    path('edit/<post_id>/', PostUpdateView.as_view(), name='post_update'),
]

Python_advanced_course/Home_work_12_Django_blog/myblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('user/', include('user.urls')),
    # *staticfiles_urlpatterns(),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    ]

Python_advanced_course/Home_work_12_Django_blog/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup')
]

Python_advanced_course/Home_work_12_Django_blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ header }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    {% block static %}
    {% endblock %}
</head>
<body>

<H5>USER: <strong>{{ user }}</strong></H5>
{% block mainmenu %}
<p class="section">
<strong><a href="{% url 'blog:view_all'%}">Main page &nbsp&nbsp&nbsp </a></strong>
<strong><a href="{% url 'blog:all_category_view'%}">All categories &nbsp;&nbsp&nbsp&nbsp </a></strong>
<strong><a href="{% url 'user:signup'%}">Registratiom  &nbsp;&nbsp&nbsp&nbsp</a></strong>
<strong><a href="{% url 'user:login'%}">Login &nbsp;&nbsp&nbsp&nbsp</a></strong>
{% if user.is_active %}
<strong><a href="{% url 'blog:view_add'%}">Add new post  &nbsp;&nbsp&nbsp&nbsp</a></strong>
{% endif %}
{% if user.is_staff %}
    <strong><a href="{% url 'blog:add_category'%}">Add new category  &nbsp;&nbsp&nbsp&nbsp</a></strong>
{% endif %}
<strong><a href="{% url 'user:logout'%}">Logout  &nbsp;&nbsp&nbsp&nbsp</a></strong>
</p>
{% endblock mainmenu %}

{% block content %}
{% endblock content %}

</body>
</html>